Add test step for test-report (possibly)

diff --git a/.github/workflows/test.yml b/.github/workflows/test.yml
--- a/.github/workflows/test.yml
+++ b/.github/workflows/test.yml
@@ -21,5 +21,12 @@ jobs:
           npm install
       - name: Install `firebase-tools` module globally
         run: npm install -g firebase-tools@13.22.0
-      - name: Run `npm run test` (firebase emulators:exec)
-        run: npm run test
+      - name: Run test
+        run: firebase emulators:exec --only auth,functions,firestore,hosting,pubsub 'npm run test_jest_only'
+      # If no test report are generated, handle this as a failure
+      - name: Check if test report exists
+        run: |
+          if [ ! -f "test-report.xml" ]; then
+            echo "No test report found"
+            exit 1
+          fi
